import './globals.css'

export const metadata = {
  title: 'RETURN POLICY',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ fontFamily: 'Ubuntu, sans-serif' }}>
        {children}
      </body>
    </html>
  )
}
